apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
    spec:
      containers:
        - name: user-ui
          image: iamjoydevdas/user-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-ui-service
spec:
  selector:
    app: user-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
